language: python
python:
    - "2.7"
git:
    submodules: false
sudo: false
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
          - g++-5
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CC="gcc-5";
        export CXX="g++-5";
        export LINK="gcc-5";
        export LINKXX="g++-5";
    fi
  - $CC --version
  - $CXX --version
  - make --version
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - make
script:
  - make test
notifications:
    irc: "irc.freenode.org#sota"
